### ISSUE TITLE
Make databaseRefreshTugboat() able to handle non-mysql database client names

### ISSUE THREAD

**Issue by apotek** [ChromaticHQ/chq-robo#159]
## Description

Given that tugboatQA now has deprecated the use of the `mysql` command in their images in favor of `mariadb`, the following lines of code need to be able to handle this change:

```php
            $result = $this->taskExec('mysql')
                ->option('-h', 'mariadb')
                ->option('-u', 'tugboat')
                ->option('-ptugboat')
                ->option('-e', "drop database if exists $dbName; create database $dbName;")
                ->run();
```

The wrapping code does some auto-discovery of credentials, and it would be ideal if we could also auto-discover from the Drupal settings whether to use `mysql` or `mariadb` (or any other db). 

However, Drupal appears not to support a `mariadb://` connection string, so we are stuck with either:

1) Running an exec against the system like `which mysql` to see if mysql is installed and then flip to mariadb if not (or vice a versa)
2) Setting the db client command in robo.yml.

## Issue Owner
@apotek /  [JFK Library](https://jfklfoundation.atlassian.net/browse/CJFK-513)

## Acceptance Criteria

- [ ] All users of Usher can easily use `mariadb` instead of `mysql` when running the `databaseRefreshTugboat()` command (or, ideally, any refresh db command). 

## Proposed Solution

1. Discover which command to do based on binaries available on the current environment, or
2. Configure which command to use in robo.yml.

## Alternatives Considered

Auto-discover from the Drupal db connection string.

**Comment by adamzimmermann** [comment]
This issue description is 🔥 .

**Comment by markdorison** [comment]
> Running an exec against the system like which mysql to see if mysql is installed and then flip to mariadb if not (or vice a versa)

Would this work in a Tugboat application container? I haven't thought about this deeply before, but the `mysql` client must be installed in the PHP container. Will _both_ the Mariadb and MySQL client be installed by default going forward? 🤔 

> Setting the db client command in robo.yml.

I would be fine with this. Even if we don't love it, it could be an interim step.

**Comment by apotek** [comment]
I think I am going to write a "BinResolver" task, where the initial parameter is the command you wish to run on a system, and the second parameter is an array of alternative commands that could be run. 

```php
/**
 * Choose which binary to use in a given system.
 *
 * @param string $binary
 *   The preferred binary or path to binary to see if the system supports.
 *
 * @param array $alternatives
 *   An array of alternative binaries or paths to binaries.
 * 
 * @return string 
 *   The path to the binary to actually execute.
 */
public function binResolver(string $binary, array $alternatives):string {}

```

I could either contribute this as a PR to the Robo tool (because it is of such a general, IO/System nature) or add it to Usher.

**Comment by adamzimmermann** [comment]
I like it.

**Comment by apotek** [comment]
This is resolved in https://github.com/ChromaticHQ/usher/pull/164
