### ISSUE TITLE
PHPStan configuration value deprecated: checkMissingIterableValueType 

### ISSUE THREAD

**Issue by markdorison** [ChromaticHQ/chq-robo#212]
## Description

The PHPStan configuration value `checkMissingIterableValueType` has been deprecated:

```
  You're using a deprecated config option checkMissingIterableValueType ⚠️️

It's strongly recommended to remove it from your configuration file
and add the missing array typehints.

If you want to continue ignoring missing typehints from arrays,
add missingType.iterableValue error identifier to your ignoreErrors:

parameters:
	ignoreErrors:
		-
			identifier: missingType.iterableValue

```

## Proposed Solution

"Remove it from your configuration file and add the missing array typehints."

## Alternatives Considered

"Add missingType.iterableValue error identifier to ignoreErrors."

**Comment by apotek** [comment]
This was fixed in #222
