### ISSUE TITLE
Resolve conflict between usher's coder implementation and coder 8.3.14

### ISSUE THREAD

**Issue by apotek** [ChromaticHQ/chq-robo#94]
## Description

Coder 8.3.14 introduces a change to how it wants to be configured. Running 8.3.14 with the old `--config-set installed_paths` option will result in the following phpcs error:

```
ERROR: Referenced sniff "SlevomatCodingStandard.ControlStructures.RequireNullCoalesceOperator" does not exist
```

Possible solution?: We'll need to create a release of usher that is glued to 8.3.13 and then create a new version of usher, moving forward, that does away with the `--config-set installed_paths` in its coder invocation. 

Workarounds for now are to issue `composer require drupal/coder:8.3.13` and pin your application to the older version of coder. Up until now, if a project used robo, you did not need to require coder as it was installed by usher. But now, with usher installing an incompatible version of coder, you need to pin it , in order to move forward.

## Documentation
Drupal Issue: https://www.drupal.org/project/coder/issues/3262291
Superb blog post on the issue: https://gorannikolovski.com/blog/referenced-sniff-slevomat-coding-standard-does-not-exist

**Comment by adamzimmermann** [comment]
I started looking into this and couldn't find `installed_paths` anywhere in this codebase.

Additionally, none of our other projects have encountered this. Maybe they just haven't done the coder update?

**Comment by adamzimmermann** [comment]
@apotek does this address your concern?

- https://github.com/ChromaticHQ/usher/commit/24854f5a44faf571bad81dd782cfe57109a569d1

**Comment by apotek** [comment]
> @apotek does this address your concern?
> 
>     * [24854f5](https://github.com/ChromaticHQ/usher/commit/24854f5a44faf571bad81dd782cfe57109a569d1)

Nice find. So it appears that some time after Usher 2.5.0, this issue was addressed. So it is no longer an active issue in releases above 2.5. 

I am stuck at Usher 2.5, which is why it remains an issue for me on Poets, but poets is (Drupal 8) an outlier, so I'm going to close this issue.
